### ISSUE TITLE
Porting `underscore` utils to `lodash`

### ISSUE THREAD

**Issue by jvduf** [AmpersandJS/ampersand-state#127]
Currently working on this. Expect to be done Jan 18th 2015.

**Comment by lukekarrys** [comment]
Renamed since we will be using lodash per https://blog.andyet.com/2015/03/25/amped-down. I think work could be done to base this conversion off the great work in #131

**Comment by wraithgar** [comment]
https://github.com/AmpersandJS/ampersand-state/pull/150
