### ISSUE TITLE
If a prop has values, allow default to specify the default value out of the values array

### ISSUE THREAD

**Issue by pgilad** [AmpersandJS/ampersand-state#129]
That is instead of specifying the same item value again in default.

For example:
```js
        showAddSubscriptionText: {
            type: 'string',
            default: 'Add Subscription'
            values: ['Add Subscription', 'Hide']
        }
```

Is a little too repeating for `default` value.

Maybe something like:
```js
        showAddSubscriptionText: {
            type: 'string',
            defaultIndex: 0,
            values: ['Add Subscription', 'Hide']
        }
```

**Comment by latentflip** [comment]
Hey @pgilad 

Thanks for the idea! My gut says the benefit of this is pretty minimal, and while not particularly hard to implement, adds more complexity to ampersand-state and it's documentation, so may not be worth it overall.

Interested to see if that's just me, or what other people think?

**Comment by HenrikJoreteg** [comment]
Hey, @pgilad. Thanks for the suggestion, I would tend to agree with @latentflip here. While I see some benefit in terms of less code, i could also see it potentially being confusing to have a default that wasn't part of the "valid options" if you will. Going to close this unless there's strong objections.
