### ISSUE TITLE
Setting a 'date' prop to null doesn't work as expected

### ISSUE THREAD

**Issue by callumlocke** [AmpersandJS/ampersand-state#143]
When constructing a new state, I am initializing a date property using some ternary logic like this:

```js
new Foo({
   endDate: (someVar ? new Date(someVar) : null)
});
```

It turns out that when the prop is initialised as `null`, it actually sets the date to Jan 1 1970.

If you change the `null` to `undefined`, then this fixes the problem. But `null` and `undefined` should behave the same here, right?

**Comment by callumlocke** [comment]
ha I just tried to fix this and then noticed your last commit fixes it.

any chance of bumping and publishing this? :)

**Comment by bear** [comment]
what commit or PR was the fix made in? I can then poke the module lead about your question

**Comment by callumlocke** [comment]
The latest commit in master

**Comment by bear** [comment]
v4.4.5 has been published

**Comment by callumlocke** [comment]
thanks!
