### ISSUE TITLE
'model' undefined when trying to pass property in extend

### ISSUE THREAD

**Issue by kellycampbell** [AmpersandJS/ampersand-state#144]
I was getting the following error in my app:
`Uncaught TypeError: Cannot read property 'model' of undefined`

This is at line 540 of ampersand-state.js

I can reproduce it in the simple hello project generated by ampersand generator:

Add props to base.js:
```
module.exports = View.extend({
    props: {
        'title': ['string', false, '']
    },
```
Pass a title in info.js to PageView.extend:
```
module.exports = PageView.extend({
    'title': 'more info',
```

I'm not sure if this is even considered a proper way to initialize a property, but the error handling on it could be much nicer to help newbies figure out what they did wrong.

**Comment by latentflip** [comment]
Hey @kellycampbell, yeah, _generally_ you don't want to initialize properties like that in an extend, but in the initializer. That said, I can see what you're trying to do here, as in your case it's _kind of_ a "class" property. 

If it's just a static value, you can just create it on the view, without having to set it as a prop first. Or, if you want it to be a dynamic property but with a default, you coud do:

```
module.exports = PageView.extend({
  props: {
    title: ['string', true, 'more info']
  }
});
```

Agreed though, that this error is pretty weird, and we could try and catch it more cleanly.

**Comment by pgilad** [comment]
After the fix in https://github.com/AmpersandJS/ampersand-state/commit/ab899efec34c739cbaa393228003c1f0f515fd16
Throws an error with 
```
Uncaught Error: You may be trying to `extend` a state object with "title" which has been defined in `props` on the object being extended
```

Hope that solves the issue!
