### ISSUE TITLE
Update readme to mention ENUM

### ISSUE THREAD

**Issue by callumlocke** [AmpersandJS/ampersand-state#149]
The docs say that `toggle` can cycle through "ENUM" properties. But there is no other mention of "ENUM" anywhere. Is it supported?

**Comment by wraithgar** [comment]
on a property you can define `values` to limit what can be set to an enumerated list.

**Comment by callumlocke** [comment]
ah, yes. I used to know that :)

I'll leave this open for now in case someone wants to clarify the readme
