### ISSUE TITLE
npm-repo version mismatch

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-state#154]
In npm, the latest version number is `4.4.5` (released a month ago), while in the repo, the latest version is `4.4.4`

I don't think it affects anything adversely, but just in case it hasn't been noticed…

**Comment by wraithgar** [comment]
Not sure how this happened. We'll fix it when we patch release for switching to lo-dash, which I will do now.  @bear any clue what happened? andyet is listed as the publisher of 4.4.5

**Comment by latentflip** [comment]
Looks like the bump commit and tag were never pushed back to GH.

**Comment by bear** [comment]
yep, i must have forgotten to push them, my local projects dir shows it pending! gah!

**Comment by wraithgar** [comment]
4.4.6 is pushed, and 4.5.0 looks like it's about to go out so this is well in the rearview now https://github.com/AmpersandJS/ampersand-state/pull/152
