### ISSUE TITLE
Derived properties that depend on a collection property out of sync

### ISSUE THREAD

**Issue by imlucas** [AmpersandJS/ampersand-state#161]
[see example on requirebin](http://requirebin.com/?gist=1a68cfc8d87c255794dc)

This is super subtle, but something that confounds my team all the time. Even though I manually trigger a change event on the collection, `record_count` is never properly recomputed and so while I have two items being rendered correctly in the `ListView`, it will always say `0 records`.

Managed to track this all the way back down to `ampersand-state` and have a fix I'm working on a PR for.

**Comment by latentflip** [comment]
Heads up on a PR for this, we've had various discussions about the best way to address this, and never quite come to a conclusion, so, probably requires some discussion before a PR can happen.

Not sure where right now, but some here for sure: https://github.com/AmpersandJS/ampersand-state/issues/66

**Comment by wraithgar** [comment]
This is ultimately a problem of tracking collection state, from my perspective.  Discussion for that started here https://github.com/AmpersandJS/ampersand-collection/issues/48

**Comment by imlucas** [comment]
Thanks!  I've been trying to find the discussion on this for quite some time now.
