### ISSUE TITLE
`parent` passed in model constructor's options is undefined

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-state#168]
I'm trying to pass in a model (or collection) as an option in a model's constructor function, but it doesn't seem to set. Setting it after instantiation seems to work, however.

For example:

````javascript
var State = require("ampersand-state");
var Model = State.extend({
	props: {
		id: "string"
	}
});

var parent = new Model({
    id: "1"
});

var child = new Model({
    id: "2",
    parent: parent
});

child.parent === undefined; //true
child.parent = parent; //setting it explicitly after initialisation
child.parent === parent; //true
````

Am I doing something wrong? I noticed that the README's section on the constructor says:

> [parent] {AmpersandState} - pass a reference to a state's parent to store on the state.

which suggests that what I'm doing should work.

I noticed that there aren't any tests for a parent being passed in the constructor options, so perhaps at some point this had worked, but there was a regression later on?

**Comment by pgilad** [comment]
You need to initiate options using the 2nd argument:
```js
var child = new Model({
    id: "2"
}, { parent: parent });
```

See https://github.com/AmpersandJS/ampersand-state/blob/master/ampersand-state.js#L36

**Comment by dhritzkiv** [comment]
Oh, right. The line-break in the documentation through me off. Thanks for replying so quickly!
