### ISSUE TITLE
Misleading error message from state extension

### ISSUE THREAD

**Issue by CrowdHailer** [AmpersandJS/ampersand-state#171]
I have been digging through my code to work out what was throwing this error.

> Uncaught Error: You may be trying to `extend` a state object with "ready" which has been defined in `props` on the object being extended

Turned out it was caused by me trying to define a method called 'showMenu' which had previously been defined in sessions. I think it should be reported as a bug that it is not correctly warning 
This was the full state object
```js
var Main = State.extend({
    session: {
        ready: {
            type: 'boolean',
            default: false
        },
        opened: {
            type: 'boolean',
            default: false
        },
        showMenu: {
            type: 'boolean',
            default: false
        }
    },
    derived: {
        loadStatus: {
            deps: ['ready'],
            fn: function () {
                return this.ready ? 'Ready! Click to begin' : 'Loading...';
            },
        }
    },
    open: function (attribute) {
        this.opened = true;
    },
    showMenu: function () {
        this.showMenu = true;
    }
});
```

**Comment by CrowdHailer** [comment]
This is a direct link to the commit with that problem for reference
https://github.com/CrowdHailer/level/commit/b32cecc26d8bc0a970b5ba4311f000d7b253bc00

**Comment by latentflip** [comment]
So this exact code does replicate the bug: 

```js
// require() some stuff from npm (like you were using browserify)
// and then hit Run Code to run it on the right
var State = require('ampersand-state');

var Main = State.extend({
    session: {
        ready: {
            type: 'boolean',
            default: false
        },
        opened: {
            type: 'boolean',
            default: false
        },
        showMenu: {
            type: 'boolean',
            default: false
        }
    },
    derived: {
        loadStatus: {
            deps: ['ready'],
            fn: function () {
                return this.ready ? 'Ready! Click to begin' : 'Loading...';
            },
        }
    },
    open: function (attribute) {
        this.opened = true;
    },
    showMenu: function () {
        this.showMenu = true;
    }
});

var m = new Main();
//console.log(m);
```

I have almost got my head around why, but not quite, exactly, will take a look in a bit.

**Comment by pgilad** [comment]
I already have a solution for this in place in `ampersand-view` (https://github.com/AmpersandJS/ampersand-view/pull/128)
It still needs work, but the discussion aims at adding this to `ampersand-state` and using it to safely assign properties to the instance.

**Comment by pgilad** [comment]
Fixed by https://github.com/AmpersandJS/ampersand-state/commit/ab899efec34c739cbaa393228003c1f0f515fd16
