### ISSUE TITLE
no change event from uncached derived properties with no dependencies

### ISSUE THREAD

**Issue by weepy** [AmpersandJS/ampersand-state#172]
Hi, I'm finding that there's no change event from uncached derived properties with no dependencies

```
var Test_state = AmpersandState.extend({
  derived: {
    time: {
       cache: false,
       fn: function() {
          return Date.now() 
       }
    }
  }
})


var test_state = new Test_state()
test_state.on('change:time', function(a,b) { 
	console.log(a,b, "XXXXX") 
})

var x = test_state.time 
/// :(

```

Am I doing something wrong ?

**Comment by lukekarrys** [comment]
If there are no `deps`, then there is nothing to trigger the change event, so you're not doing anything wrong, but that code won't work as you expect.

You could use the `trigger` method (similar to my comment on https://github.com/AmpersandJS/ampersand-state/issues/173#issuecomment-111569447) to trigger you change handlers for `time`:

```js
var Test_state = require('ampersand-state').extend({
  derived: {
    time: {
       cache: false,
       fn: function() {
          return Date.now() 
       }
    }
  }
})


var test_state = new Test_state()
test_state.on('change:time', function() { 
    console.log(test_state.time) 
})

test_state.trigger('change:time')
```

**Comment by weepy** [comment]
I guess I to do this I should mixin "ampersand-events" ?

**Comment by lukekarrys** [comment]
`ampersand-state` already has `ampersand-events` mixed in, so the above code should work out-of-the-box.

**Comment by weepy** [comment]
you're right - thanks for the patience - my bad!
