### ISSUE TITLE
cid should be more private or at least parsable

### ISSUE THREAD

**Issue by bryanspears** [AmpersandJS/ampersand-state#185]
The key `cid` is a potential breaking point for any developer that does not have control over their API data. `cid` cannot be set (`Uncaught TypeError: Cannot read property 'cid' of null`) and it cannot be parsed (same error as set).

It either needs to be made "truly private" (via closure or similar), pseudo-private (`_cid`), or give us the ability to parse `cid` out of the data.

**Comment by latentflip** [comment]
What do you mean by "parse cid out of the data"?

You should be able to remap data incoming from your api to use a different attribute for your cid property in the model. You can use a combination of parse and serialize, either on the model or the collection, to manipulate data on the way in and out of your model: http://ampersandjs.com/docs#ampersand-state-parse

**Comment by bryanspears** [comment]
Odd. I was in a situation moments ago where parsing cid out of the response data failed with the above error. Now it's working as intended. Sorry for the false alarm, but it happened somehow.

If I'm able to figure out how I caused the error again I'll re-open and add notes here.

**Comment by latentflip** [comment]
Worth noting that parse is only called on server responses or if you set parse: true as options. If you just do "new Model({ cid: "foo" })" parse will not be called.

Philip Roberts
&yet
