### ISSUE TITLE
Document props depending on properties from other state objects (e.g. via children or state props)

### ISSUE THREAD

**Issue by callumlocke** [AmpersandJS/ampersand-state#186]
Do either of these work?

```js
var Foo = State.extend({
  props: {
    stateProp: 'state'
  },

  children: {
    child: Something,
  },

  derived: {
    thing: {
      deps: ['stateProp.something'], // depending on a property of a state prop
      fn: function () { ... },
    },

    thing2: {
      deps: ['child.something'], // depending on a property of a formal child state
      fn: function () { ... },
    },
  }
});
```

Or is there any other formal way for derived props to depend on props from another state object?

**Comment by lukekarrys** [comment]
Sorry for the lack of response on this! :grin: From looking at the code, I think that should work. If you're still having problems with this can you reopen?

**Comment by callumlocke** [comment]
My experiments found it sometimes works and sometimes doesn't. I'm not clear on whether this is by design or not, because the capability is never mentioned in the docs.

Can you reopen this as a documentation issue?

**Comment by lukekarrys** [comment]
Also I made a gist to show an example based on your initial code which is working in a requirebin: http://requirebin.com/?gist=4ee5530421686ccca330

**Comment by ConneXNL** [comment]
It seems that stateProp.someDerivedProperty doesn't work.

Also having just "stateProp" has dependency also doesn't work whereas "stateProp.id" does.
