### ISSUE TITLE
Nested props triggering 'change' a.k.a "Deep Model Behaviour"

### ISSUE THREAD

**Issue by orenmizr** [AmpersandJS/ampersand-state#191]
(will try to label this as question, discussion, enhancement)
```
{
    id: 123,
    user: {
        type: 'Spy',
        age: 20,
        name: {
            first: 'Sterling',
            last: 'Archer'
        }
    },
    otherSpies: [
        { name: 'Lana' },
        { name: 'Cyrril' }
    ]
}
```

lets assume this is the props of the model/state. now if we do app.instance.**user.age** = 21 -> anyone listening in to change on that model/state wouldn't be aware of it. 

is there a way to enable this? or to extend the state without refactoring it that much

**Comment by kamilogorek** [comment]
To achieve this, you can use `childern` property.

```js
var User = AmpersandState.extend({
    props: {
        type: 'string',
        age: 'number',
        (...)
    },
});

{
    id: 123,
    children: {
        user: User
    },
    otherSpies: [
        { name: 'Lana' },
        { name: 'Cyrril' }
    ]
}
```

**Comment by lukekarrys** [comment]
I made a gist for #186 and I think its relevant here too. It shows how to depend on `children` or `props` with a `type` of `state` for derived properties. But the idea is the same for if other models want to listen to them as well. http://requirebin.com/?gist=4ee5530421686ccca330

**Comment by orenmizr** [comment]
@lukekarrys. clever use of dependency and state to achieve that. wish there were more examples online for various scenarios. thanks.

**Comment by lukekarrys** [comment]
@orenmizr Yeah we need some more documentation for the nested stuff. I kept #186 open to track adding some documentation about that.
