### ISSUE TITLE
toJSON does not serialize state props

### ISSUE THREAD

**Issue by wasd171** [AmpersandJS/ampersand-state#197]
Well, it's in the title. Collections and children are serialized, but pure props of type `state` aren't

**Comment by cdaringe** [comment]
hmm.  toJSON calls serialize without any args, and [serialize adds props by default](https://github.com/AmpersandJS/ampersand-state/blob/master/ampersand-state.js#L107). requirebin?

**Comment by wasd171** [comment]
It doesn't call .serialize on props. Only on children and collections. So if you design a state prop it won't be serialized
