### ISSUE TITLE
Better handling of multiple collections.

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-state#2]
I'd like to switch to some way of better handling collections that contain a model. Perhaps adding a addCollectionReference method that the collection calls if present.

**Comment by superscript18** [comment]
What's the state of adding this?  I'm moving over from Backbone-relational and really need a way to do reverse relations to multiple collections.

Is this feature not going to be considered (it looks like it might break things)?
Or is there better way to get this behavior?
