### ISSUE TITLE
After upgrading to nunjucks 2 I'm unable to access getters on object in the template

### ISSUE THREAD

**Issue by dschissler** [AmpersandJS/ampersand-state#204]
The following quick getter test works with nunjucks 2 and proves that it does know how to use the getters:

```javascript
'use strict';
let nunjucks = require('nunjucks');

let html;

let o1 = {
  _value: 'abc',
  get value() {
    return this._value;
  }
}
// Ouputs 'abc'
console.log(o1.value);
html = nunjucks.renderString('{{o.value}}', {o: o1});
// Ouputs 'abc'
console.log(html);

let O2 = function() {
  this._value = 'abc';
  Object.defineProperty(this, 'value', {
    get: function() { return this._value }
  });
}
let o2 = new O2();
html = nunjucks.renderString('{{o.value}}', {o: o2});
// Ouputs 'abc'
console.log(html);
```

Something is wrong with either `ampersand-view` or `ampersand-state` because the following template doesn't work with nunjucks 2 but does work with nunjucks 1:

```javascript
{{ model.type }}
```

but the following does work:

```javascript
{{ _values['model']['_values']['type'] }}
```

Above I determined that `nunjucks@2.*` works with getters and now it is coming down to either `ampersand-state`, ampersand-view` or the webpack loader `nunjucks-loader@2.*`.  nunjucks-loader is just passing in the context so I don't see how that could be an issue.

**Comment by dschissler** [comment]
I've posted an identical issue at [nunjucks-loader](https://github.com/at0g/nunjucks-loader/issues/17) because that project was updated (ampersand wasn't) and I've determined that `nunjucks` is handling the getter correctly.

**Comment by latentflip** [comment]
Any chance you can build a repo where this is replicated and working? I tried to get nunjucks working with browserify to replicate your example above and I can't even get that to load (nunjucks doesn't seem to be properly designed to work with browserify)?

**Comment by dschissler** [comment]
I think that I just found the issue with nunjucks and so I reopen the issue there.

**Comment by latentflip** [comment]
Okay, reopen this if you think it's an ampersand issue.

**Comment by dschissler** [comment]
Its probably not an issue here but it is in the sense that probably many frameworks are using getters and so they may not be handling the case correctly.

**Comment by latentflip** [comment]
Yeah, there's not a lot we can do about that though unless we serialize objects before passing them into the template, which would throw away things like methods. Will just have to get template engines to fix it if it comes up again.

**Comment by dschissler** [comment]
Its a nunjucks issue for sure and it is a regression from 1 to 2.  That project has 2000 stars and 58,000 downloads in the last month and nobody spotted this, nor are they testing for it.  I think that just shows how few projects are using getters (because of IE8 compatibility).
