### ISSUE TITLE
Runtime crash when using custom types

### ISSUE THREAD

**Issue by gvilarino** [AmpersandJS/ampersand-state#214]
Hi, I'm experiencing a constant, deterministic crash in my ampersand app since today. The error message I get is:

```
Uncaught TypeError: Invalid data type of `SubCollection` for `widgets` property. Use one of the default types or define your own
```

The only thing I did was clear my `npm` cache and reinstall. All my `ampersand` versions are pinned so I'm sure the error comes from the unpinned deps in `ampersand`'s  module deps (probably `ampersand-model`, although I'm not sure since there are no changelogs available).

My deps versions are:

```
"ampersand-collection": "1.5.0"
"ampersand-collection-underscore-mixin": "1.0.4"
"ampersand-collection-view": "1.4.0"
"ampersand-form-view": "2.4.0"
"ampersand-input-view": "3.1.1"
"ampersand-model": "5.0.3"
"ampersand-react-view-mixin": "0.0.5"
"ampersand-rest-collection": "2.0.4"
"ampersand-router": "1.0.7"
"ampersand-subcollection": "2.0.3"
"ampersand-view": "7.4.2"
"ampersand-view-switcher": "1.1.2"
```

More context: my first error wasn't about `Subcollection` but about using `'*'` instead of `'any'` as a prop type. Once I fixed that, I started seeing the above error.

This breaks my build on prod :(

**Comment by scottbert** [comment]
I have a similar issue at the moment:

```javascript
import State from 'ampersand-state';
import geoTools from './geo-tools';

const AppState = State.extend({
    props: {
        lat: 'float',
        long: 'float',
........
    extraProperties: 'allow'
```
etc...
Leads to "Uncaught TypeError: Invalid data type of `float` for `lat` property. Use one of the default types or define your own"

**Comment by gvilarino** [comment]
FWIW here's my stack trace up until the first appearance of an `ampersand` module

```
Uncaught TypeError: Invalid data type of `SubCollection` for `widgets` property. Use one of the default types or define your own
createPropertyDefinition @ ampersand-state.js:575
(anonymous function) @ ampersand-state.js:792
(anonymous function) @ index.js:40
baseForOwn @ index.js:23
(anonymous function) @ index.js:38extend @ ampersand-state.js:791
...
```

**Comment by latentflip** [comment]
It's caused by this: https://github.com/AmpersandJS/ampersand-state/blob/master/ampersand-state.js#L575 IMO we should back out this, and change from being a throw to a console.warn. Thoughts @kamilogorek @pgilad?

**Comment by pgilad** [comment]
@latentflip Definitely agree that without a `major` version bump, throwing an error is very bad behavior for us :cry: 
Revert to `console.warn` sounds great...

**Comment by latentflip** [comment]
If someone can PR it, I'll +1 it.

**Comment by STRML** [comment]
I had this happen in development as well, found it very useful because previously no warning was being thrown. I agree that it should not be an `Error` until a major version bump.

**Comment by pgilad** [comment]
Released under https://github.com/AmpersandJS/ampersand-state/commit/1324b2905f6a65b034c2f8178ded05fcbd092ce5

**Comment by wraithgar** [comment]
Thanks for making this issue @gvilarino

**Comment by gvilarino** [comment]
Thanks to you guys! Go Ampersand!
