### ISSUE TITLE
overriding functions fails since 5.0.0

### ISSUE THREAD

**Issue by vwasteels** [AmpersandJS/ampersand-state#232]
Hi !

I'm overriding the parse function to transform some properties, I modify directly the prototype so it will affect all parse further...

something like this :
```js
**
 * Server to client inflection.
 * Converts properties from snakecase to camelcase.
 */

State.prototype._parse = function(attrs) {
	_.each(attrs, _.bind(function(val, name) {

		// snake_case -> camelCase
		if (~name.indexOf('_')) {
			var newName = _.camelCase(name);
			attrs[newName] = val;
			delete attrs[name];
			name = newName;
		}

		// booleans
		var def = this._definition[name];
		if (null != def && 'boolean' == def.type)
			attrs[name] = (attrs[name] ? true : false);

	}, this));
	return attrs;
};

State.prototype.parse = function(attrs) {
	return this._parse(attrs);
};
```

and then in my model, for example, I can do :
```js
        // ...
        parse: function(attrs) {
		attrs = this._parse(attrs);
		attrs.date = moment.unix(attrs.date);
		return attrs;
	},
```

That worked well until I updated ```ampersand-state``` to ```5.0.0``` , and now I get this error in the browser : ```Uncaught TypeError: this._parse is not a function```

Are you aware of a change in the module structure that could explain this ?

Thanks !!

**Comment by latentflip** [comment]
My best guess would be that you have somehow ended up with two copies of ampersand-state (perhaps one module depends on `4.x` and another on `5.x`, and so when you modify ampersand-state in one place, it's actually a different prototype to the one being used by your model?

**Comment by latentflip** [comment]
Looking at ampersand-model, this seems likely, since ampersand-model doesn't yet depend on ampersand-state `5.x`, in the meantime I would pin your package.json to `4.8.2` for ampersand-state, or just modify the prototype on ampersand-model instead of ampersand-state.

**Comment by vwasteels** [comment]
thanks for the answer, I just downgraded ampersand-state to ```4.8.2``` and it works !
