### ISSUE TITLE
use lodash modules, not full

### ISSUE THREAD

**Issue by jlit** [AmpersandJS/ampersand-state#244]
AFAIK, all the other ampersand modules use the individual lodash modules but state is using the full library, thus doubling the download size for lodash.

**Comment by cdaringe** [comment]
hey @jlit, take a peek at the src: https://github.com/AmpersandJS/ampersand-state/blob/master/ampersand-state.js#L6

bundlers will not bundle the full lodash module because the root module is not in the require path.

ping us w/ further qs. thx
