### ISSUE TITLE
Is there an equivilent to hasOwnProperty for ampersand models?

### ISSUE THREAD

**Issue by jlit** [AmpersandJS/ampersand-state#248]
Not sure how to differentiate between a model that doesn't support a property and one that does but currently has a value of undefined.  

```
module.exports = BaseModel.extend({
  props: {
    id:            [ 'string', false ],
    title:         [ 'string', false ],
etc...
```

```
item.extraProperties
"ignore"
item.title
"this is the title"
item.hasOwnProperty('title')
false
```

**Comment by coder13** [comment]
Really late reply but hopefully at least useful to people searching for a solution:

I found 2 ways of doing this.
Using __proto__:
`item.__proto__._definition` will have the prop as an object. In this case .title is
```js
{
  type: 'string',
  default: undefined,
  allowNull: false,
  test: undefined,
  values: undefined
}
```

You can use `Object.keys(item.__proto__._definition)` to get all the props or `!!item.__proto__._definition.title` to see if the prop exists.

Way 2:
`item._values` is an object with all the properties. While .title will be undefind, you can use `Object.keys(item._values)` to see all the props and use `.indexOf('title') !== -1` on the keys to see if exists.

Hope this helps. I could keep digging but it doesn't look like there's a simple direct way of doing this.

**Comment by jlit** [comment]
@coder13 Thanks.
