### ISSUE TITLE
collections and child properties not working when packed by react native

### ISSUE THREAD

**Issue by faxioman** [AmpersandJS/ampersand-state#250]
When I try to use 'collections' or 'child' property inside a react native app I always get:

```
this._collections[coll] is not a function
```
or 
```
this._children[child] is not a function
```

**Comment by dhritzkiv** [comment]
When you're defining the collections or children on the State, are you passing in a constructor of a collection/child, or an instance of a collection/child?

**Comment by faxioman** [comment]
I'm passing a constructor:

```
...
collections: {
   subEvents: MySubEventCollection
}
...
```

**Comment by dhritzkiv** [comment]
Hmm. Very curious. Nothing else stands out as to why this might be happening. I'm also not at all familiar with ReactNative or its toolset to begin to suspect any issues there.

Does passing an unadulterated collection also produce the same error?

```js
//import AmpersandState and AmpersandCollection, somehow

const MyState = AmpersandState.extend({
    collections: {
        subEvents: AmpersandCollection.extend({})
    }
});

const myState = new MyState();
```

**Comment by faxioman** [comment]
It was a problem in my import chain. Unfortunately the error message confused me.
May it be worthwhile to check that the collection is not null?
Anyway, thanks for your suppor! ;)
