### ISSUE TITLE
Type casting

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-state#29]
It'd be nice to have automatic type casting when setting certain property values that aren't of the correct property data type, namely text to number or number to text.

For example: say we have a model like so:

````
{
    props: {
        cost: "number",
        month: "text"
    }
}
````

and we try to use `set` on the model:

````
var date = new Date();
model.set({
    cost: "24.01",
    month: date.getMonth()// returns 7
})
//throws: "TypeError: Property 'cost' must be of type number. Tried to set 24.01"
````

neither of the values are set (an error is thrown). Is there a way to do automatic typecasting?

**Comment by HenrikJoreteg** [comment]
Given that the docs added by @mmacaula in #103 have been merged, i'm closing this one. #cleanupallthethings
