### ISSUE TITLE
'reject' for properties set after instantiation?

### ISSUE THREAD

**Issue by callumlocke** [AmpersandJS/ampersand-state#33]
Even if you set `extraProperties: 'reject'`, it's still possible to set a random property on the object later. Is it possible to throw an error when an undeclared property is set? (I'm not sure if there is any way to do this in JS but thought I'd ask..)

Also, btw, it the readme doesn't say what the default is for `extraProperties`

**Comment by callumlocke** [comment]
OK. Please close this if it seems undoable.

**Comment by kamilogorek** [comment]
Alright, thanks!
