### ISSUE TITLE
Custom validation functions for props?

### ISSUE THREAD

**Issue by callumlocke** [AmpersandJS/ampersand-state#34]
Would you be interested in a PR to add per-property validation? So instead of an array of allowed `values`, you could provide a function that would return true or false, and Ampersand State would throw an error if you try to set a value that doesn't pass.

e.g.

```js
props: {
  somethingThatHasToBeEven: {
    type: 'number',
    validate: function (value) {
       return value % 2 === 0;
    }
  }
}
```

**Comment by callumlocke** [comment]
thanks @wraithgar

**Comment by tiagorg** [comment]
I found this today after searchin the issues and was able to solve my problem by using ```test```. I wonder why is it not documented? Would this be deprecated, can I use it in production, would there by any other issue?

**Comment by latentflip** [comment]
@tiagorg simply because the people who wrote a lot of the documentation (i.e. me) missed it :) There's no reason not to use it that I'm aware of, or plans to remove it.

Please feel free to submit a PR adding it to the docs if you like :)

**Comment by tiagorg** [comment]
Gotcha @latentflip! Very well, just added to the docs (sent you a PR). If you think that looks good it might also be worth writing something to https://ampersandjs.com/learn/state/ - then please let me know the repo for that one.

**Comment by latentflip** [comment]
@tiagorg here: https://github.com/AmpersandJS/ampersandjs.com/blob/gh-pages/learn_markdown/state.md
