### ISSUE TITLE
Constants and/or read-only attributes

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand-state#37]
There are lots of apis out there that, for reasons outside the scope of ampersand caring, have attributes that are either constants (always the same for models of this type) or read only (will never and can never change for a given model instance).

Currently for constants one can set the prop to {type: 'string', values: ['constantValue']} but that seems a little longhanded for a constant.

Also, this doesn't address the issue of a value that needs to be in props (i.e. included in state syncs to the server) but should generate helpful errors clientside if changed to help protect you from yourself.

This issue is a discussion/feature request for these things.

**Comment by HenrikJoreteg** [comment]
closing since @kamilogorek addressed this in docs.
