### ISSUE TITLE
Passing an initialized collection to a State constructor

### ISSUE THREAD

**Issue by ConneXNL** [AmpersandJS/ampersand-state#43]
When you pass an initialized collection to a State constructor it won't detect that the collection is already initialized. Instead it will read it as an object and wrap it in a new collection.

Is there a way to bypass the auto-initialization in constructors.
Could this be achieved by type-checking?

Example which does not work:
var myCollection = new MyCollection();
var myState = new MyState({someChildCollection: myCollection });

Exampe that does work:
var myCollection = new MyCollection();
var myState = new MyState();
myState.someChildCollection = myCollection;

**Comment by pgilad** [comment]
Closing this as this is dated almost a year ago. Feel free to re-open
