### ISSUE TITLE
Should not instantiate collections with empty array

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-state#49]
doing this: 

```js
this[coll] = new this._collections[coll]([], {parent: this});
```

means that if we in the collection's `initialize` method add some models by using `add()` they'll be removed by the subsequent `reset` call.

At first glance i think the problem would be solved by just doing:

```js
this[coll] = new this._collections[coll](null, {parent: this});
```

But this needs some tests to confirm.

**Comment by lukekarrys** [comment]
The code in question was changed by https://github.com/AmpersandJS/ampersand-state/commit/fd1c64b2e5fd503cbe9a9b690cb7f69436904832#diff-8a9bf6b5d6e0c56925dadb3c3f2ae1b5R430. This is closed by that commit.
