### ISSUE TITLE
Array modifier functions don't trigger change event

### ISSUE THREAD

**Issue by remixz** [AmpersandJS/ampersand-state#50]
If I use a method like `Array.prototype.push` or `Array.prototype.splice` on an array in a model, it doesn't trigger a change event, since it's not directly setting the array. This is definitely an edge case, but it'd be cool if doing `model.array.push(foo)` just worked. I'm working around it by adding this to my view:

```js
addItem: function (item) {
    var arr = _.clone(this.model.array);
    arr.push(item);
    this.model.array = arr;
}
```

The only solution I can think of would be that when there's an array in a model, those sort of methods are extended with some extra code, and then, using `push` as an example, `Array.prototype.push.apply(this, arguments)` is called at the end. I'm not sure if it's worth the effort to do that though, as it's not a super common case, and adding a view method isn't that bad. I figured I'd report it though, just for potential feedback. Thanks!

**Comment by pgilad** [comment]
Yeah, you cannot be notified of array changes without proxying array methods or possibly Array.observe (ES7).
The best workaround is as you guys found out, to clone the array and reassign it after the manipulation.
*I would definitely document this*.

Another possible solution is to use child collections, which obviously trigger events on change/add/remove. (they proxy the array methods).

**Comment by pgilad** [comment]
Closing this.. Reopen as needed.
