### ISSUE TITLE
Error on invalid property type

### ISSUE THREAD

**Issue by meetthelegend** [AmpersandJS/ampersand-state#56]
Discovered a bug where I had an invalid property type, and it probably should have thrown an error.

**Comment by pgilad** [comment]
Trace this into this piece of code: https://github.com/AmpersandJS/ampersand-state/blob/master/ampersand-state.js#L523-L537

On both occasions - if type doesn't pass `_ensureValidType` it is ignored.
The easiest solution is after parsing property definition, and type isn't defined (would be `undefined`) then an error could be thrown.

This breaks backward compatibility, and it's not what users may expect.

Currently the docs do no handle this case. It could possibly default to `any`.

**Comment by pgilad** [comment]
@cdaringe @bear Should we throw on invalid prop/session type? (Not one of the pre-defined and of the custom dataTypes) ?

**Comment by cdaringe** [comment]
uh oh!  yea, we should definitely address this. ease of use is requirement :)  thanks for the fiddle @brianberlin!

**Comment by HenrikJoreteg** [comment]
we know all valid types, and custom types, it seems logical and quite helpful to throw if there's one that doesn't match.
