### ISSUE TITLE
Borrow features from Backbone.Epoxy

### ISSUE THREAD

**Issue by markerikson** [AmpersandJS/ampersand-state#57]
Been working on a Backbone app for the last year, and Ampersand looks like it solves a lot of the issues I've run into.  I've been using the Backbone.Epoxy plugin, which has enhanced Model and View classes.

Epoxy.Model includes computed properties, which AmpersandState has as well.  However, the main thing that AmpersandState is missing compared to Epoxy is the ability to set computed properties.  Here's an example from the Epoxy docs:

```javascript
model.addComputed("formattedPrice", {
    deps: ["price"],
    get: function( price ) {
        return "$"+ price;
    },
    set: function( value ) {
        return {price: parseInt(value.replace("$", ""))}
    }
});
```

Not necessarily a critical feature, but I could see it being useful.

Epoxy also automatically determines dependencies by parsing or listening for .get() calls while initializing a computed property, although that one I definitely don't see as critical.

**Comment by pgilad** [comment]
@markerikson Feel free to add a PR for this, currently closing because this issue is pretty old
