### ISSUE TITLE
Instantiating a model with collections should use add.

### ISSUE THREAD

**Issue by mysterycommand** [AmpersandJS/ampersand-state#58]
Hi, ran into an interesting problem today where I have a model that defines a collection of models that define their own idAttribute. In order to get the collection to de-duplicate it's children on instantiation I have to set `mainIndex` on the collection *and* pass `{ remove: false }` to the parent model's constructor.

Here's some code:

```javascript
var State = require('ampersand-state');
var Collection = require('ampersand-collection');

var Child = State.extend({
    idAttribute: 'idx',
    props: {
        idx: ['string']
    }
});

var GoodCollection = Collection.extend({
    mainIndex: 'idx',
    model: Child
});

var BadCollection = Collection.extend({
    model: Child
});

var Parent = State.extend({
    props: {
        name: ['string']
    },
    collections: {
        childA: GoodCollection
        childB: BadCollection
    }
});

var mom = new Parent({
    name: 'Mom',
    childrenA: [{
        idx: 'abc'
    }, {
        idx: 'abc'
    }, {
        idx: 'def'
    }],
    childrenB: [{
        idx: 'abc'
    }, {
        idx: 'abc'
    }, {
        idx: 'def'
    }]
}, { remove: false });
// mom.childrenA.length = 2
// mom.childrenB.length = 3

var dad = new Parent({
    name: 'Dad',
    childrenA: [{
        idx: 'abc'
    }, {
        idx: 'abc'
    }, {
        idx: 'def'
    }],
    childrenB: [{
        idx: 'abc'
    }, {
        idx: 'abc'
    }, {
        idx: 'def'
    }]
});
// dad.childrenA.length = 3
// dad.childrenB.length = 3
```

… this may also be related to [ampersand-collection issue 19](https://github.com/AmpersandJS/ampersand-collection/issues/19) and [ampersand-collection issue 20](https://github.com/AmpersandJS/ampersand-collection/issues/20). I *believe* that a solutions would be to split the if statement at [line 143](https://github.com/AmpersandJS/ampersand-state/blob/master/ampersand-state.js#L143) and in the case of a collection call `.add` instead of set (it defaults the options differently than `.set` does itself).

cc @jedireza

**Comment by pgilad** [comment]
Hey @mysterycommand was this fixed?

**Comment by mysterycommand** [comment]
@pgilad, I'm trying to reach back a year in my mind and I'm not 100% sure if this was fixed, or if I just figured out what my problem was and worked around it. TBH, I haven't been working with `ampersand-state` for most of this year.

**Comment by pgilad** [comment]
Alright, I'll just close this assuming it is, and we can always reopen if it's relevant for anyone else
