### ISSUE TITLE
Computed default properties should be idempotent

### ISSUE THREAD

**Issue by lipsmack** [AmpersandJS/ampersand-state#60]
If a property is undefined but has a default value, we reference the default every time the property is accessed. Where the default value is returned from a function, this means that the value is calculated on every single access. This creates a problem for computed, non-deterministic defaults. I expect this also creates problems for array and object properties, as we repeatedly create new objects and discard references to the previous object.

For example, I created a model that generates a UUID if no ID is provided. I would expect this value to remain the same, but I see the following:

```javascript
var Test = Model.extend({
    props: {
        id: {
            type: "string",
            default: function() {
                return uuid.v4();
            }
        }
    }
});

var t = new Test();
t.id === t.id; // false
```

It would be better if property defaults behaved the same way as defaults in Backbone - i.e. applied to the model only once, on instantiation.

**Comment by latentflip** [comment]
This was fixed by #114, closing.
