### ISSUE TITLE
Nested `session` property states don't dispatch change.

### ISSUE THREAD

**Issue by lukasbuenger** [AmpersandJS/ampersand-state#91]
Imagine a scenario where you have a model that represents certain values and additionally should have a session property that represents the UI state the model is in:

```javascript
var State = AmpersandState.extend({
	props: {
		isFocused: {
			type: 'boolean',
			'default': false
		}
	}
});

var Model = AmpersandState.extend({
	props: {
		name: {
			type: 'string',
			'default': 'Unknown'
		}
	},
	session: {
		state: {
			type: 'object',
			'default': function () {
				return new State();
			}
		}
	}
});
```

The session property `state` gets correctly created:
```javascript
foo = new Model();
console.log(foo.state);

// Object: {cid: .... }
``` 

But now, it would be nice to be able to listen to changes happening on that very `state` session property. The following won't trigger anything:
```javascript
foo = new Model();
foo.on('change', function (model) {
	console.log('Listener on parent model: ', model.state.isFocused);
});
model.state.isFocused = true;
```

This probably works as designed as you don't *always* necessarily want to delegate session changes to the parent model. But this actually should be working as we are referring to a simple AmpersandState object. But it isn't:
```javascript
foo = new Model();
foo.state.on('change', function(state) {
	console.log('Listener on session model: ', state.isFocused);	
});
foo.state.isFocused = true;
```

Is this intentional?

**Comment by lukekarrys** [comment]
I think some of the reworking of how the default function works in #114 and #118. I tested with the code in the previous comment and everything works as expected now.
